[env:esp32-s3-devkitc-1]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

; PSRAM bắt buộc cho audio buffer
board_build.arduino.memory_type = qio_opi

; Serial monitor
monitor_speed = 115200

; Lib tự động cài
lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S.git
    bblanchon/ArduinoJson @ ^7.0.0

; Build flags
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
