[env:esp32dev]
platform  = espressif32@6.9.0
board     = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S.git#2.0.6
    bblanchon/ArduinoJson @ ^7.0.0
    olikraus/U8g2 @ ^2.35.19

build_flags =
    -Wno-error=narrowing
    -DMIC_SCK=14 -DMIC_WS=15 -DMIC_SD=34
    -DSPK_BCLK=26 -DSPK_LRC=25 -DSPK_DIN=22
    -DSPK_VOLUME=15 -DBTN_PIN=0
    -DOLED_SDA=21 -DOLED_SCL=19 -DOLED_ADDR=0x3C
    -DSAMPLE_RATE=16000 -DRECORD_SECONDS=3
